syntax on
"set number
"set hlsearch
colorscheme molokai


"from http://stevelosh.com/blog/2010/09/coming-home-to-vim/#core-differences
execute pathogen#infect()
filetype plugin indent on

if has('gui_running')
  set guifont=Menlo\ Regular:h13
endif

set nocompatible

set modelines=0


set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set relativenumber
set undofile

nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
nnoremap <tab> %
vnoremap <tab> %

set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=85

set list
set listchars=tab:▸\ ,eol:¬

au FocusLost * :wa

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>
nnoremap ; :
inoremap jj <ESC>


nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

autocmd vimenter * if !argc() | NERDTree | endif
let NERDTreeQuitOnOpen=1



"""""""""""""""""""""""""""LEADERS"""""""""""""""""""""""""
let mapleader = ","

"Clear search
nnoremap <leader><space> :noh<cr>

"VSplit with current file
nnoremap <leader>s <C-w>v<C-w>l

"Jump to definition
nnoremap <leader>t <C-]>

"Open NerdTree
nnoremap <leader>nt :NERDTree<cr>

""Find files
nnoremap <leader>ff :CtrlPMixed<cr>

"Find tags
nnoremap <leader>tf :CtrlPTag

"Tagbar
nmap <F8> :TagbarToggle<CR>

